### PR TITLE
Option to hide print label button in orders listing page

### PR DESCRIPTION
**Pull request by gadnis**
This is a feature to hide "Print label" button next to every single order.
There is maybe good thing to have it there for some merchants but for some it is useless and takes space on the admin orders page.

With this pull request merchant introduced with the option to be able to hide "Print label" column on the admin orders page.

Pros (when "Print label" column is hidden):
- faster page load
- easier to focus on the page
- still have an option to select the order or more than one and print labels with bulk action
Cons:
- module contributor will have to find a time to check and merge the pull request 😁 

Screenshots:
[Settings page](https://prnt.sc/OFxNp5HWHWu8)

### CODE REVIEW

**Comment by justelis22** [comment]
Hello there @gadnis,

We will check with the DPD team, and let you know what is decided.

Best Regards,
Invertus Support team.

**Comment by gadnis** [comment]
@justelis22  any news?

**Comment by justelis22** [comment]
Hi there @gadnis,

The fix will be included in the upcoming 3.2.18 release, which we plan on releasing this month.
We have not included this feature in the current release as we had more urgent cases.

Thank you for your patience!

**Comment by GytisZum** [comment]
Closing this ticket as this functionality is included in release `3.2.18`

**Pull request closed without merging**
